

services:
  ai-redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  ai-minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  ai_fastapi:
    build: ./fastapi_app
    container_name: ai_fastapi
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=ai-redis
      - REDIS_PORT=6379
      - MINIO_HOST=ai-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - ai-redis
      - ai-minio

  ai_trainer_worker:
    build: ./trainer_worker
    container_name: ai_trainer_worker
    environment:
      - REDIS_HOST=ai-redis
      - REDIS_PORT=6379
      - MINIO_HOST=ai-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - ai-redis
      - ai-minio
